sudo: true
dist: trusty

notifications:
  email: false

services:
  - docker

install:
  - cd docker; ./build.sh
  - docker images

matrix:
  include:
    - env: lint check
      script: docker run arraiy/torchgeometry /bin/bash -c "source path.bash.inc && python verify.py --check lint"

    - env: static check
      script: docker run arraiy/torchgeometry /bin/bash -c "source path.bash.inc && python verify.py --check mypy"

    - env: docs
      script: docker run arraiy/torchgeometry /bin/bash -c "source path.bash.inc && python verify.py --check build-docs"

    - env: test
      script: docker run arraiy/torchgeometry /bin/bash -c "source path.bash.inc && pytest test/"
