language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
  - ./setup_travis_env.sh
  - source path.bash.inc

install:
  - python setup.py install

matrix:
  include:
    - env: lint check
      script: python verify.py --check lint
    
    - env: static check
      script: python verify.py --check mypy
    
    - env: docs
      script: python verify.py --check build-docs
    
    - env: unit tests
      script: pytest -vx --cov=torchgeometry test
      after_success:
        - bash <(curl -s https://codecov.io/bash)
