language: python
python:
  - "3.6"

notifications:
  email: false

before_install:
  - ./setup_travis_env.sh
  - source path.bash.inc

install:
  - make install

matrix:
  include:
    - env: lint check
      script: make lint
    
    - env: static check
      script: make mypy
    
    - env: docs
      script: make build-docs
    
    - env: unit tests
      script: make test-cpu-cov
      after_success:
        - bash <(curl -s https://codecov.io/bash)
