version: 2

common: &common
  working_directory: ~/kornia-tester
  steps:
    - checkout
    - run:
        name: run setup-dev-env
        command: ./setup_travis_env.sh
    - run:
        name: activate enviroment
        command: |
          source path.bash.inc
          echo "source .dev_env/bin/activate" >> $BASH_ENV
    - run:
        name: install package
        command: make install
    - run:
        name: lint check
        command: make lint
    - run:
        name: static check
        command: make mypy
    - run:
        name: docs
        command: make build-docs
    - run:
        name: unit tests
        command: make test-cpu-cov
    - run:
        name: send coverage
        when: on_success
        command: bash <(curl -s https://codecov.io/bash)

jobs:
  "python-3.6":
    <<: *common
    docker:
      - image: circleci/python:3.6.5

  "python-3.7":
    <<: *common
    docker:
      - image: circleci/python:3.7.3

workflows:
  version: 2
  test:
    jobs:
      - "python-3.6"
        #- "python-3.7"
